image: migamake/haskell-build:8.6

stages:
  - build
  - test
  - release

variables:
  PACKAGE_NAME:       json-autotype
  EXEC_NAME:          json-autotype
  DOCKER_TLS_CERTDIR: "/certs"
  PACKAGE_VER: "3.0.3"

services:
  - docker:19.03.1-dind

cache:
  paths:
    - .stack-work
    - .cabal-sandbox
    - /root/.cabal
    - /root/.stack


stack_build:
  image: migamake/haskell-build:8.6
  stage: build
  script:
    - ci/stack-build.sh
  allow_failure: true
  retry: 2

# Build for images up to 8.6, with `cabal-install` 2.x

.build_exe:
  image: migamake/haskell-build:$GHC_VER
  stage: build
  script:
    - ci/old-cabal-build.sh
  retry: 2

# Build for images 8.8 and above with `cabal-install` v3.x

.new_build_exe:
  image: migamake/haskell-build:$GHC_VER
  stage: build
  script:
    - ci/new-cabal-build.sh
  retry: 2

ghc_8_6:
  variables:
    GHC_VER: "8.6"
  extends: .build_exe
  artifacts:
    paths:
      - sdist/*[0-9].tar.gz
      - hackage-docs/*-docs.tar.gz
      - bin/${EXEC_NAME}
    expire_in: 2 weeks
  allow_failure: false

ghc_8_4:
  variables:
    GHC_VER: "8.4"
  extends: .build_exe

ghc_8_10:
  variables:
    GHC_VER: "8.10"
  extends: .new_build_exe
  retry: 2
  allow_failure: true

ghc_8_8:
  variables:
    GHC_VER: "8.8"
  extends: .new_build_exe
  retry: 2
  allow_failure: true

tar_package:
  stage: test
  script:
    - cabal update
    - mkdir -p bin
    - cabal install sdist/$PACKAGE_NAME*[0-9].tar.gz --bindir=bin/
    - tar xzf sdist/$PACKAGE_NAME*[0-9].tar.gz
    - bin/${EXEC_NAME} json-autotype/test/colors.json
  dependencies:
    - ghc_8_6
  artifacts:
    paths:
      - bin/${EXEC_NAME}
  allow_failure: false

docker_image:
  image: docker
  stage: build
  script:
    - mkdir -p workdir
    - docker build . -t migamake/${PACKAGE_NAME} -f Dockerfile
    - docker run -v $PWD/lib:/workdir migamake/${PACKAGE_NAME}
    - docker save --output ${PACKAGE_NAME}.docker migamake/${PACKAGE_NAME}:latest
    - ls -alth ${PACKAGE_NAME}.docker
  artifacts:
    paths:
      - ${PACKAGE_NAME}.docker

candidate_hackage:
  stage: test
  script:
    - ci/release.sh
  dependencies:
    - ghc_8_6
  environment:
    name: "hackage-candidate-${PACKAGE_VER}"
    url:  "https://hackage.haskell.org/package/homplexity-${PACKAGE_VER}/candidate"
  only:
    - master
  allow_failure: true

hackage:
  stage: release
  script:
    - ci/release.sh --publish
  dependencies:
    - ghc_8_6
  when: manual
  only:
    - master

dockerhub:
  image: docker
  stage: release
  script:
    - docker load -i ${PACKAGE_NAME}.docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    - docker push migamake/json-autotype;
  dependencies:
    - docker_image
  when: manual
  only:
    - master

