image: migamake/haskell-build:8.6.2

stages:
  - build
  - test
  - release

cache:
  paths:
    - .stack-work
    - .cabal-sandbox

.build_exe:
  image: migamake/haskell-build:$GHC_VER
  stage: build
  script:
    - cabal sandbox init
    - cabal --version
    - ghc   --version
    - cabal update
    - cd json-alt
    - cabal install
    - cabal sdist   --builddir=../sdist/
    - cabal haddock --builddir=../hackage-docs/ --for-hackage
    - cd ../json-autotype
    - "sed --in-place 's/-- STATIC: //' json-autotype.cabal"
    - cabal install --only-dependencies --enable-tests --enable-benchmarks
    - cabal test
    - mkdir -p bin sdist
    - cabal install --bindir=../bin/
    - cabal sdist   --builddir=../sdist/
    - cabal haddock --builddir=../hackage-docs --for-hackage

build_8_6_2:
  variables:
    GHC_VER: 8.6.2
  extends: .build_exe
  artifacts:
    paths:
      - sdist/json-alt-*[0-9].tar.gz
      - hackage-docs/json-alt-*-docs.tar.gz
      - sdist/json-autotype-*[0-9].tar.gz
      - hackage-docs/json-autotype-*-docs.tar.gz
      - bin/json-autotype
    expire_in: 2 weeks

build_8_4_4:
  variables:
    GHC_VER: 8.4.4
  extends: .build_exe

build_8_2_2:
  variables:
    GHC_VER: 8.2.2
  extends: .build_exe

build_8_0_2:
  variables:
    GHC_VER: 8.0.2
  extends: .build_exe
  retry: 2
  allow_failure: true

build_7_10_3:
  variables:
    GHC_VER: 7.10.3
  extends: .build_exe

build_7_8_4:
  variables:
    GHC_VER: 7.8.4
  extends: .build_exe

test_distribution:
  stage: test
  script:
    - cabal update
    - mkdir -p bin
    - cabal install sdist/json-alt*[0-9].tar.gz --bindir=bin/
    - cabal install sdist/json-autotype*[0-9].tar.gz --bindir=bin/
    - tar xzf sdist/json-autotype*[0-9].tar.gz
    - bin/json-autotype --output parseExamples.hs json-autotype-*/examples/*.json
  dependencies:
    - build_8_6_2
  artifacts:
    paths:
      - json-autotype/bin/json-autotype

stack_build:
  image: migamake/haskell-build:8.6.2
  stage: build
  script:
    - echo "$CI_ENVIRONMENT_SLUG"
    - stack --version
    - stack setup
    - stack build
    - stack test
  allow_failure: true

pier_build:
  image: migamake/haskell-build:8.6.2
  stage: build
  script:
    - pier build --no-shared-cache
    - pier test  --sandbox
  allow_failure: true

release_to_hackage:
  stage: release
  script:
    - cabal upload --username="$HACKAGE_USER" --password="$HACKAGE_PASSWORD" sdist/json-alt-*[0-9].tar.gz
    - cabal upload --username="$HACKAGE_USER" --password="$HACKAGE_PASSWORD" -d hackage-docs/json-alt-*-docs.tar.gz
    - cabal upload --username="$HACKAGE_USER" --password="$HACKAGE_PASSWORD" sdist/json-autotype-*[0-9].tar.gz
    - cabal upload --username="$HACKAGE_USER" --password="$HACKAGE_PASSWORD" -d hackage-docs/json-autotype-*-docs.tar.gz
  environment:
    name: release
    url:  https://hackage.haskell.org/package/json-autotype
  dependencies:
    - build_8_6_2
  when: manual
  only:
    - master
