version: 2
jobs:
  build:
    docker:
      - image: migamake/haskell-build
    environment:
      PATH: $HOME/.local/bin:$PATH
    steps:
      - checkout
      - run:
          name:    Setup
          command: stack setup
      - run:
          name:    Install
          command: stack install
      - run:
          name:    Test
          command: stack test
      - run:
          name:    Make distribution archive
          command: stack sdist
      - run:
          name:    Create artifacts directory
          command: |
            mkdir -p /tmp/artifacts;
            cp .stack-work/dist/*/Cabal-*/json-autotype-*.tar.gz /tmp/artifacts/json-autotype.tar.gz
      - store_artifacts:
          path:        /tmp/artifacts/json-autotype.tar.gz
